export default {
  'game.title': 'ANGKOR',
  'game.subtitle': 'Legacy of the Khmer Empire',
  'loading.env': 'Preparing Angkor Wat…',
  'loading.veg': 'Growing the forest…',
  'loading.world': 'Waking the temple…',
  'title.new': 'New Journey',
  'title.continue': 'Continue',
  'title.settings': 'Settings',
  'title.language': 'ភាសាខ្មែរ / English',
  'title.note': 'A work of historical fiction set at a real monument. Historical notes are researched; characters, puzzles and in-game artifacts are fictional and labelled as such.',
  'title.click': 'Click to begin',

  'hud.objective': 'Current Objective',
  'hud.artifacts': 'Artifacts',
  'hud.interact': 'INTERACT',
  'hud.discover': 'Discover',
  'hud.talk': 'Talk',
  'hud.inspect': 'Inspect',
  'hud.pickup': 'Pick up',
  'hud.activate': 'Activate',
  'hud.place': 'Place stone',
  'hud.rotate': 'Rotate mirror',
  'hud.read': 'Read',
  'hud.photo': 'Take in the view',
  'hud.saved': 'Game saved',
  'hud.autosaved': 'Autosaved',
  'hud.chapter': 'Chapter',
  'hud.newObjective': 'New objective',
  'hud.objectiveDone': 'Objective complete',
  'hud.discovered': 'Location discovered',
  'hud.artifactDiscovered': 'Artifact Discovered',
  'hud.journalUpdated': 'Angkor Journal updated',
  'hud.puzzleSolved': 'Puzzle solved',
  'hud.fps': 'FPS',

  'hint.move': 'WASD / left stick to move · mouse / right stick to look · Shift to sprint · V to walk',
  'hint.interact': 'Walk up to glowing markers and press E to discover history',
  'hint.jump': 'Space to jump · C to crouch · F for first-person view',
  'hint.menu': 'Esc for the menu · M for the map · J for the Angkor Journal',
  'hint.water': 'The water is too deep to wade into.',
  'hint.fell': 'You found your footing again.',
  'hint.bounds': 'That way leads away from Angkor Wat.',
  'hint.barrier': 'Closed for conservation work. The western stairway is the way up.',
  'hint.doorLocked': 'The stone mechanism is missing pieces.',
  'hint.pointerLock': 'Click the game to control the camera',
  'hint.needPieces': 'You need the missing stone pieces.',
  'hint.sequenceReset': 'The stones fall silent. Try another order.',
  'hint.reliefs': 'The survey markers are beside the great reliefs of the outer gallery. Walk it with the temple on your left.',
  'hint.reliefReset': 'That is not the order of the story. The panels reset.',

  'menu.continue': 'Continue',
  'menu.map': 'Map',
  'menu.journal': 'Angkor Journal',
  'menu.artifacts': 'Artifacts',
  'menu.objectives': 'Objectives',
  'menu.settings': 'Settings',
  'menu.controls': 'Controls',
  'menu.language': 'Language',
  'menu.save': 'Save Game',
  'menu.exit': 'Exit to Title',
  'menu.paused': 'Paused',
  'menu.saveManual': 'Save to manual slot',
  'menu.loadManual': 'Load manual save',
  'menu.loadAuto': 'Load autosave',
  'menu.empty': 'Empty',
  'menu.savedAt': 'Saved',
  'menu.exitConfirm': 'Return to the title screen? Unsaved progress since the last autosave will be lost.',
  'menu.yes': 'Yes',
  'menu.no': 'No',

  'journal.locations': 'Places',
  'journal.artifacts': 'Artifacts',
  'journal.people': 'People',
  'journal.reliefs': 'Bas-Reliefs',
  'journal.facts': 'Fact & Fiction',
  'journal.empty': 'Nothing recorded yet. Explore to fill your journal.',
  'journal.period': 'Period',
  'journal.khmerName': 'Khmer name',
  'journal.architecture': 'Architectural significance',
  'journal.history': 'History',
  'journal.context': 'Historical context',
  'journal.ingame': 'In this game',
  'journal.fictional': 'Fictional',
  'journal.researched': 'Researched',
  'journal.sources': 'Sources consulted',
  'journal.undiscovered': 'Undiscovered',

  'objectives.current': 'Current',
  'objectives.done': 'Completed',
  'objectives.optional': 'Optional',

  'artifact.rotate': 'Drag to rotate · wheel to zoom',
  'artifact.add': 'Add to Collection',
  'artifact.close': 'Close',
  'artifact.category': 'Category',
  'artifact.found': 'Found',

  'discovery.close': 'Continue',
  'discovery.new': 'New discovery',

  'dialogue.continue': 'Continue',
  'dialogue.end': 'Goodbye',
  'dialogue.fictional': 'Fictional character',

  'map.title': 'Angkor Wat',
  'map.you': 'You',
  'map.legend.place': 'Discovered place',
  'map.legend.objective': 'Objective',
  'map.legend.artifact': 'Artifact found',
  'map.legend.person': 'Person',
  'map.north': 'N',

  'settings.graphics': 'Graphics',
  'settings.preset': 'Quality preset',
  'settings.low': 'Low', 'settings.medium': 'Medium', 'settings.high': 'High', 'settings.ultra': 'Ultra', 'settings.custom': 'Custom',
  'settings.resolution': 'Resolution scale',
  'settings.texture': 'Texture quality',
  'settings.shadows': 'Shadow quality',
  'settings.aa': 'Anti-aliasing',
  'settings.ao': 'Ambient occlusion',
  'settings.reflections': 'Reflection quality',
  'settings.vegetation': 'Vegetation density',
  'settings.viewDistance': 'View distance',
  'settings.vsync': 'VSync',
  'settings.vsyncNote': 'Browsers always synchronise with the display; this toggles the frame-rate cap.',
  'settings.fpsLimit': 'FPS limit',
  'settings.fullscreen': 'Fullscreen',
  'settings.occlusion': 'Occlusion culling',
  'settings.showFps': 'Show FPS',
  'settings.off': 'Off', 'settings.on': 'On', 'settings.unlimited': 'Unlimited',
  'settings.fxaa': 'FXAA', 'settings.msaa': 'MSAA 4×', 'settings.baked': 'Baked', 'settings.bakedSsao': 'Baked + SSAO',
  'settings.camera': 'Camera & Controls',
  'settings.sensitivity': 'Look sensitivity',
  'settings.invertY': 'Invert Y',
  'settings.fov': 'Field of view',
  'settings.audio': 'Audio',
  'settings.master': 'Master volume',
  'settings.music': 'Music',
  'settings.ambience': 'Ambience',
  'settings.sfx': 'Effects',
  'settings.ui': 'Interface',
  'settings.time': 'Time of day',
  'settings.timeAuto': 'Story (slow)',
  'settings.sunrise': 'Sunrise', 'settings.day': 'Day', 'settings.sunset': 'Sunset', 'settings.night': 'Night',
  'settings.language': 'Language',
  'settings.back': 'Back',
  'settings.subtitlesNote': 'Khmer text is a draft translation and should be reviewed by a native speaker.',

  'controls.move': 'Move', 'controls.look': 'Look / rotate camera', 'controls.run': 'Run (default)',
  'controls.walk': 'Walk (toggle)', 'controls.sprint': 'Sprint (hold)', 'controls.jump': 'Jump', 'controls.crouch': 'Crouch (toggle)',
  'controls.interact': 'Interact / discover / pick up', 'controls.inspect': 'First-person inspection view',
  'controls.zoom': 'Camera zoom', 'controls.map': 'Map', 'controls.journal': 'Angkor Journal', 'controls.menu': 'Menu / pause',
  'controls.time': 'Next time of day (after the story ends)',
  'controls.keyboard': 'Keyboard & mouse', 'controls.gamepad': 'Controller',

  'end.title': 'Sunrise Over Angkor',
  'end.body': 'You have walked from the moat to the summit of Angkor Wat. The temple is still a living place of worship and a shared heritage of Cambodia and the world. Please visit respectfully.',
  'end.continue': 'Continue exploring',
  'end.credits': 'Environment from pet_model.blend (original procedural model). Music and sound are generated in real time and are original. Characters, puzzles and artifact placements are fictional.',

  // desktop / UI refresh
  'lang.choose': 'Choose your language',
  'lang.hint': 'You can change this any time in Settings → Language.',
  'lang.en': 'English',
  'lang.km': 'ភាសាខ្មែរ',
  'title.quit': 'Quit Game',
  'title.version': 'Version {v}',
  'title.keys': '↑ ↓ to choose · Enter to confirm',
  'loading.tip': 'Tip',
  'tip.1': 'Walk up to a glowing marker and press E to learn its history.',
  'tip.2': 'Press M for the map and J for the Angkor Journal.',
  'tip.3': 'Angkor Wat faces west, toward the setting sun.',
  'tip.4': 'The five towers represent the peaks of Mount Meru.',
  'tip.5': 'Autosave runs after every discovery, artifact and puzzle.',
  'menu.autoSlot': 'Autosave',
  'menu.manualSlot': 'Manual save',
  'menu.back': 'Esc · Back',
  'menu.resume': 'Resume',
  'controls.mouse': 'Mouse',
  'controls.wheel': 'Wheel',
  'controls.lstick': 'Left stick',
  'controls.rstick': 'Right stick',
  'controls.lstickFull': 'Left stick (full)',
  'controls.lstickHalf': 'LB / left stick (half)',
  'controls.dpad': 'D-pad ↑↓',
  'settings.display': 'Display',
};
