// Khmer UI strings. Draft translation – to be reviewed by a native Khmer speaker before release.
export default {
  'game.title': 'អង្គរ',
  'game.subtitle': 'កេរដំណែលនៃចក្រភពខ្មែរ',
  'loading.env': 'កំពុងរៀបចំប្រាសាទអង្គរវត្ត…',
  'loading.veg': 'កំពុងដាំព្រៃឈើ…',
  'loading.world': 'កំពុងដាស់ប្រាសាទ…',
  'title.new': 'ចាប់ផ្តើមដំណើរថ្មី',
  'title.continue': 'បន្ត',
  'title.settings': 'ការកំណត់',
  'title.language': 'ភាសាខ្មែរ / English',
  'title.note': 'នេះជារឿងប្រឌិតបែបប្រវត្តិសាស្ត្រ ដែលកើតឡើងនៅវិមានពិតប្រាកដ។ ព័ត៌មានប្រវត្តិសាស្ត្រត្រូវបានស្រាវជ្រាវ ចំណែកតួអង្គ ល្បែងផ្គុំ និងវត្ថុបុរាណក្នុងហ្គេម គឺជារឿងប្រឌិត ហើយត្រូវបានសម្គាល់យ៉ាងច្បាស់។',
  'title.click': 'ចុចដើម្បីចាប់ផ្តើម',

  'hud.objective': 'គោលដៅបច្ចុប្បន្ន',
  'hud.artifacts': 'វត្ថុបុរាណ',
  'hud.interact': 'ធ្វើអន្តរកម្ម',
  'hud.discover': 'ស្វែងយល់',
  'hud.talk': 'និយាយ',
  'hud.inspect': 'ពិនិត្យ',
  'hud.pickup': 'រើសយក',
  'hud.activate': 'ធ្វើឱ្យដំណើរការ',
  'hud.place': 'ដាក់ថ្ម',
  'hud.rotate': 'បង្វិលកញ្ចក់',
  'hud.read': 'អាន',
  'hud.photo': 'មើលទេសភាព',
  'hud.saved': 'បានរក្សាទុកហ្គេម',
  'hud.autosaved': 'បានរក្សាទុកដោយស្វ័យប្រវត្តិ',
  'hud.chapter': 'ជំពូក',
  'hud.newObjective': 'គោលដៅថ្មី',
  'hud.objectiveDone': 'បានបំពេញគោលដៅ',
  'hud.discovered': 'បានរកឃើញទីតាំង',
  'hud.artifactDiscovered': 'បានរកឃើញវត្ថុបុរាណ',
  'hud.journalUpdated': 'កំណត់ហេតុអង្គរត្រូវបានធ្វើបច្ចុប្បន្នភាព',
  'hud.puzzleSolved': 'បានដោះស្រាយល្បែងផ្គុំ',
  'hud.fps': 'FPS',

  'hint.move': 'WASD / ដងបញ្ជាខាងឆ្វេង ដើម្បីដើរ · កណ្តុរ / ដងបញ្ជាខាងស្តាំ ដើម្បីមើល · Shift ដើម្បីរត់លឿន · V ដើម្បីដើរយឺត',
  'hint.interact': 'ដើរទៅជិតសញ្ញាភ្លឺ ហើយចុច E ដើម្បីស្វែងយល់ពីប្រវត្តិសាស្ត្រ',
  'hint.jump': 'Space ដើម្បីលោត · C ដើម្បីអោន · F សម្រាប់ទិដ្ឋភាពមនុស្សទីមួយ',
  'hint.menu': 'Esc សម្រាប់ម៉ឺនុយ · M សម្រាប់ផែនទី · J សម្រាប់កំណត់ហេតុអង្គរ',
  'hint.water': 'ទឹកជ្រៅពេក មិនអាចដើរចុះបានទេ។',
  'hint.fell': 'អ្នកបានឈរជើងឡើងវិញ។',
  'hint.bounds': 'ផ្លូវនោះនាំឆ្ងាយពីប្រាសាទអង្គរវត្ត។',
  'hint.barrier': 'បិទសម្រាប់ការងារអភិរក្ស។ ជណ្តើរខាងលិចជាផ្លូវឡើង។',
  'hint.doorLocked': 'យន្តការថ្មខ្វះបំណែកមួយចំនួន។',
  'hint.pointerLock': 'ចុចលើហ្គេមដើម្បីបញ្ជាកាមេរ៉ា',
  'hint.needPieces': 'អ្នកត្រូវការបំណែកថ្មដែលបាត់។',
  'hint.sequenceReset': 'ថ្មស្ងាត់ឈឹង។ សូមសាកល្បងលំដាប់ផ្សេង។',
  'hint.reliefs': 'សញ្ញាស្ទង់ស្ថិតនៅក្បែរចម្លាក់លៀនធំៗនៃរោងខាងក្រៅ។ សូមដើរដោយឱ្យប្រាសាទនៅខាងឆ្វេង។',
  'hint.reliefReset': 'នោះមិនមែនជាលំដាប់នៃរឿងទេ។ ផ្ទាំងចម្លាក់ត្រូវបានកំណត់ឡើងវិញ។',

  'menu.continue': 'បន្ត',
  'menu.map': 'ផែនទី',
  'menu.journal': 'កំណត់ហេតុអង្គរ',
  'menu.artifacts': 'វត្ថុបុរាណ',
  'menu.objectives': 'គោលដៅ',
  'menu.settings': 'ការកំណត់',
  'menu.controls': 'ការបញ្ជា',
  'menu.language': 'ភាសា',
  'menu.save': 'រក្សាទុកហ្គេម',
  'menu.exit': 'ត្រឡប់ទៅទំព័រដើម',
  'menu.paused': 'បានផ្អាក',
  'menu.saveManual': 'រក្សាទុកក្នុងរន្ធដោយដៃ',
  'menu.loadManual': 'បើកការរក្សាទុកដោយដៃ',
  'menu.loadAuto': 'បើកការរក្សាទុកស្វ័យប្រវត្តិ',
  'menu.empty': 'ទទេ',
  'menu.savedAt': 'បានរក្សាទុក',
  'menu.exitConfirm': 'ត្រឡប់ទៅទំព័រដើម? វឌ្ឍនភាពដែលមិនទាន់រក្សាទុកចាប់តាំងពីការរក្សាទុកស្វ័យប្រវត្តិចុងក្រោយនឹងបាត់បង់។',
  'menu.yes': 'បាទ/ចាស',
  'menu.no': 'ទេ',

  'journal.locations': 'ទីកន្លែង',
  'journal.artifacts': 'វត្ថុបុរាណ',
  'journal.people': 'មនុស្ស',
  'journal.reliefs': 'ចម្លាក់លៀន',
  'journal.facts': 'ការពិត និងការប្រឌិត',
  'journal.empty': 'មិនទាន់មានអ្វីកត់ត្រានៅឡើយ។ សូមរុករកដើម្បីបំពេញកំណត់ហេតុរបស់អ្នក។',
  'journal.period': 'សម័យកាល',
  'journal.khmerName': 'ឈ្មោះខ្មែរ',
  'journal.architecture': 'សារៈសំខាន់ផ្នែកស្ថាបត្យកម្ម',
  'journal.history': 'ប្រវត្តិសាស្ត្រ',
  'journal.context': 'បរិបទប្រវត្តិសាស្ត្រ',
  'journal.ingame': 'ក្នុងហ្គេមនេះ',
  'journal.fictional': 'ប្រឌិត',
  'journal.researched': 'បានស្រាវជ្រាវ',
  'journal.sources': 'ប្រភពដែលបានពិគ្រោះ',
  'journal.undiscovered': 'មិនទាន់រកឃើញ',

  'objectives.current': 'បច្ចុប្បន្ន',
  'objectives.done': 'បានបញ្ចប់',
  'objectives.optional': 'ជម្រើស',

  'artifact.rotate': 'អូសដើម្បីបង្វិល · រមូរដើម្បីពង្រីក',
  'artifact.add': 'បញ្ចូលទៅក្នុងបណ្តុំ',
  'artifact.close': 'បិទ',
  'artifact.category': 'ប្រភេទ',
  'artifact.found': 'បានរកឃើញ',

  'discovery.close': 'បន្ត',
  'discovery.new': 'ការរកឃើញថ្មី',

  'dialogue.continue': 'បន្ត',
  'dialogue.end': 'លាហើយ',
  'dialogue.fictional': 'តួអង្គប្រឌិត',

  'map.title': 'អង្គរវត្ត',
  'map.you': 'អ្នក',
  'map.legend.place': 'ទីកន្លែងដែលបានរកឃើញ',
  'map.legend.objective': 'គោលដៅ',
  'map.legend.artifact': 'វត្ថុបុរាណដែលបានរកឃើញ',
  'map.legend.person': 'មនុស្ស',
  'map.north': 'ជ',

  'settings.graphics': 'ក្រាហ្វិក',
  'settings.preset': 'កម្រិតគុណភាព',
  'settings.low': 'ទាប', 'settings.medium': 'មធ្យម', 'settings.high': 'ខ្ពស់', 'settings.ultra': 'ខ្ពស់បំផុត', 'settings.custom': 'ផ្ទាល់ខ្លួន',
  'settings.resolution': 'កម្រិតភាពច្បាស់',
  'settings.texture': 'គុណភាពវាយនភាព',
  'settings.shadows': 'គុណភាពស្រមោល',
  'settings.aa': 'ការធ្វើឱ្យគែមរលោង',
  'settings.ao': 'ស្រមោលជុំវិញ',
  'settings.reflections': 'គុណភាពចំណាំងផ្លាត',
  'settings.vegetation': 'ដង់ស៊ីតេរុក្ខជាតិ',
  'settings.viewDistance': 'ចម្ងាយមើលឃើញ',
  'settings.vsync': 'VSync',
  'settings.vsyncNote': 'កម្មវិធីរុករកតែងតែធ្វើសមកាលកម្មជាមួយអេក្រង់ ជម្រើសនេះកំណត់ដែនកំណត់ស៊ុម។',
  'settings.fpsLimit': 'ដែនកំណត់ FPS',
  'settings.fullscreen': 'ពេញអេក្រង់',
  'settings.occlusion': 'ការលាក់វត្ថុដែលមើលមិនឃើញ',
  'settings.showFps': 'បង្ហាញ FPS',
  'settings.off': 'បិទ', 'settings.on': 'បើក', 'settings.unlimited': 'គ្មានដែនកំណត់',
  'settings.fxaa': 'FXAA', 'settings.msaa': 'MSAA 4×', 'settings.baked': 'ដុតជាមុន', 'settings.bakedSsao': 'ដុតជាមុន + SSAO',
  'settings.camera': 'កាមេរ៉ា និងការបញ្ជា',
  'settings.sensitivity': 'ភាពរសើបនៃការមើល',
  'settings.invertY': 'បញ្ច្រាសអ័ក្ស Y',
  'settings.fov': 'វាលមើលឃើញ',
  'settings.audio': 'សំឡេង',
  'settings.master': 'កម្រិតសំឡេងមេ',
  'settings.music': 'តន្ត្រី',
  'settings.ambience': 'សំឡេងបរិយាកាស',
  'settings.sfx': 'បែបផែនសំឡេង',
  'settings.ui': 'ចំណុចប្រទាក់',
  'settings.time': 'ពេលវេលានៃថ្ងៃ',
  'settings.timeAuto': 'តាមរឿង (យឺតៗ)',
  'settings.sunrise': 'ថ្ងៃរះ', 'settings.day': 'ពេលថ្ងៃ', 'settings.sunset': 'ថ្ងៃលិច', 'settings.night': 'ពេលយប់',
  'settings.language': 'ភាសា',
  'settings.back': 'ត្រឡប់ក្រោយ',
  'settings.subtitlesNote': 'អត្ថបទខ្មែរជាសេចក្តីព្រាងបកប្រែ ហើយគួរត្រូវបានពិនិត្យដោយអ្នកនិយាយភាសាខ្មែរ។',

  'controls.move': 'ដើរ', 'controls.look': 'មើល / បង្វិលកាមេរ៉ា', 'controls.run': 'រត់ (លំនាំដើម)',
  'controls.walk': 'ដើរយឺត (បិទ/បើក)', 'controls.sprint': 'រត់លឿន (សង្កត់)', 'controls.jump': 'លោត', 'controls.crouch': 'អោន (បិទ/បើក)',
  'controls.interact': 'ធ្វើអន្តរកម្ម / ស្វែងយល់ / រើសយក', 'controls.inspect': 'ទិដ្ឋភាពពិនិត្យមនុស្សទីមួយ',
  'controls.zoom': 'ពង្រីកកាមេរ៉ា', 'controls.map': 'ផែនទី', 'controls.journal': 'កំណត់ហេតុអង្គរ', 'controls.menu': 'ម៉ឺនុយ / ផ្អាក',
  'controls.time': 'ពេលវេលាបន្ទាប់ (បន្ទាប់ពីរឿងបញ្ចប់)',
  'controls.keyboard': 'ក្តារចុច និងកណ្តុរ', 'controls.gamepad': 'ឧបករណ៍បញ្ជា',

  'end.title': 'ថ្ងៃរះលើអង្គរ',
  'end.body': 'អ្នកបានដើរពីគូទឹករហូតដល់កំពូលប្រាសាទអង្គរវត្ត។ ប្រាសាទនេះនៅតែជាទីសក្ការៈបូជាដ៏រស់រវើក និងជាបេតិកភណ្ឌរួមរបស់កម្ពុជា និងពិភពលោក។ សូមទស្សនាដោយការគោរព។',
  'end.continue': 'បន្តការរុករក',
  'end.credits': 'បរិស្ថានពី pet_model.blend (គំរូដើមដែលបង្កើតតាមនីតិវិធី)។ តន្ត្រី និងសំឡេងត្រូវបានបង្កើតភ្លាមៗ ហើយជាស្នាដៃដើម។ តួអង្គ ល្បែងផ្គុំ និងទីតាំងវត្ថុបុរាណគឺជារឿងប្រឌិត។',

  // desktop / UI refresh
  'lang.choose': 'ជ្រើសរើសភាសា',
  'lang.hint': 'អ្នកអាចប្តូរភាសាបានគ្រប់ពេល នៅក្នុង ការកំណត់ → ភាសា។',
  'lang.en': 'English',
  'lang.km': 'ភាសាខ្មែរ',
  'title.quit': 'ចាកចេញពីហ្គេម',
  'title.version': 'កំណែ {v}',
  'title.keys': '↑ ↓ ដើម្បីជ្រើសរើស · Enter ដើម្បីបញ្ជាក់',
  'loading.tip': 'គន្លឹះ',
  'tip.1': 'ដើរទៅជិតសញ្ញាភ្លឺ ហើយចុច E ដើម្បីស្វែងយល់ពីប្រវត្តិរបស់វា។',
  'tip.2': 'ចុច M សម្រាប់ផែនទី និង J សម្រាប់កំណត់ហេតុអង្គរ។',
  'tip.3': 'ប្រាសាទអង្គរវត្តបែរមុខទៅទិសខាងលិច ឆ្ពោះទៅព្រះអាទិត្យលិច។',
  'tip.4': 'ប្រាង្គទាំងប្រាំតំណាងឱ្យកំពូលភ្នំព្រះសុមេរុ។',
  'tip.5': 'ហ្គេមរក្សាទុកដោយស្វ័យប្រវត្តិ បន្ទាប់ពីការរកឃើញ វត្ថុបុរាណ និងល្បែងផ្គុំនីមួយៗ។',
  'menu.autoSlot': 'ការរក្សាទុកស្វ័យប្រវត្តិ',
  'menu.manualSlot': 'ការរក្សាទុកដោយដៃ',
  'menu.back': 'Esc · ត្រឡប់ក្រោយ',
  'menu.resume': 'បន្តលេង',
  'controls.mouse': 'កណ្តុរ',
  'controls.wheel': 'កង់កណ្តុរ',
  'controls.lstick': 'ដងបញ្ជាឆ្វេង',
  'controls.rstick': 'ដងបញ្ជាស្តាំ',
  'controls.lstickFull': 'ដងបញ្ជាឆ្វេង (ពេញ)',
  'controls.lstickHalf': 'LB / ដងបញ្ជាឆ្វេង (ពាក់កណ្តាល)',
  'controls.dpad': 'D-pad ↑↓',
  'settings.display': 'ការបង្ហាញ',

  // journal, map, settings, modes, summary
  'journal.progress': 'ការរកឃើញ {n} / {of}',
  'journal.discovered': 'បានរកឃើញ',
  'journal.back': '← ត្រឡប់ទៅកំណត់ហេតុ',
  'journal.period': 'សម័យកាល',
  'journal.location': 'ទីតាំង',
  'journal.history': 'ប្រវត្តិ',
  'journal.significance': 'សារៈសំខាន់ និងស្ថាបត្យកម្ម',
  'journal.related': 'ការរកឃើញពាក់ព័ន្ធ',
  'journal.claim': 'ការអះអាង',
  'journal.fact': 'អ្វីដែលភស្តុតាងបង្ហាញ',
  'journal.verdict.fiction': 'ការយល់ខុស',
  'journal.verdict.context': 'ត្រូវការបរិបទ',
  'journal.historical': 'មនុស្សនៃអង្គរ',
  'journal.metPeople': 'មនុស្សដែលអ្នកបានជួប',
  'journal.about': 'អំពីហ្គេមនេះ',
  'journal.relief': 'ចម្លាក់លៀន',
  'journal.secret': 'សម្ងាត់',
  'hud.newDiscovery': '✦ ការរកឃើញថ្មី ✦',
  'hud.saving': 'កំពុងរក្សាទុក…',
  'hud.journalPeople': 'កំណត់ហេតុបានធ្វើបច្ចុប្បន្នភាព · មនុស្ស',
  'hud.journalFacts': 'កំណត់ហេតុបានធ្វើបច្ចុប្បន្នភាព · ការពិត និងការប្រឌិត',
  'hud.waypoint': 'ចំណុចដៅ',
  'map.zoomIn': 'ពង្រីក',
  'map.zoomOut': 'បង្រួម',
  'map.center': 'ទៅទីតាំងខ្ញុំ',
  'map.clearWaypoint': 'លុបចំណុចដៅ',
  'map.help': 'អូសដើម្បីរំកិល · កង់កណ្តុរដើម្បីពង្រីក · ចុចដើម្បីដាក់ចំណុចដៅ',
  'map.legend.waypoint': 'ចំណុចដៅ',
  'map.legend.undiscovered': 'ទីកន្លែងមិនទាន់រកឃើញ',
  'settings.gameplay': 'ការលេង',
  'settings.accessibility': 'ភាពងាយស្រួលប្រើ',
  'settings.brightness': 'ពន្លឺ',
  'settings.uiScale': 'ទំហំចំណុចប្រទាក់',
  'settings.autosave': 'រក្សាទុកស្វ័យប្រវត្តិ',
  'settings.hints': 'គន្លឹះណែនាំ',
  'settings.showObjective': 'បង្ហាញគោលដៅលើអេក្រង់',
  'settings.guidance': 'របៀបរុករក',
  'settings.guided': 'ដំណើរមានការណែនាំ',
  'settings.free': 'ការរុករកដោយសេរី',
  'settings.highContrast': 'អក្សរកម្រិតពន្លឺខ្ពស់',
  'settings.reducedMotion': 'កាត់បន្ថយចលនា និងការរង្គោះកាមេរ៉ា',
  'settings.reset': 'កំណត់ឡើងវិញ',
  'settings.resetDone': 'ការកំណត់ត្រូវបានកំណត់ឡើងវិញ',
  'mode.title': 'តើអ្នកចង់រុករកដោយរបៀបណា?',
  'mode.guidedDesc': 'គោលដៅ សញ្ញា និងគន្លឹះនាំអ្នកឆ្លងកាត់រឿងរ៉ាវនៃប្រាសាទ។',
  'mode.freeDesc': 'ដើរលេងតាមល្បឿនរបស់អ្នក ដោយមានការណែនាំតិចតួច។ រឿងរ៉ាវនៅតែបើកនៅពេលអ្នករកឃើញ។',
  'mode.back': 'ត្រឡប់ក្រោយ',
  'end.summary': 'ដំណើររបស់អ្នក',
  'end.places': 'ទីកន្លែងដែលបានរកឃើញ',
  'end.reliefs': 'ចម្លាក់លៀនដែលបានសិក្សា',
  'end.artifacts': 'វត្ថុបុរាណដែលបានរកឃើញ',
  'end.people': 'មនុស្សនៃអង្គរ',
  'end.facts': 'ការពិត និងការប្រឌិត',
  'end.total': 'ការរុករកសរុប',
  'end.remaining': 'នៅសល់ការរកឃើញ {n} ទៀត',
  'end.allFound': 'អ្នកបានរកឃើញទាំងអស់។ អស្ចារ្យណាស់។',
  'end.legacy': 'កេរដំណែលនៃអង្គរ',
  'controls.objectives': 'គោលដៅ',
};
